### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by 0xS4D** [MrH0wl/UNIngPy#1]
Hola! Sé que no es el proyecto actual, y que existe otro proyecto sobre eso, pero quería preguntar, si existe medio para contactarte sobre tu proyecto de "ML Checker" el cual me ayudaría muchísimo poder utilizarlo con una rotación de Proxy para evitar el captcha... ya que intenté muchas formas diferentes y aún no puedo solucionarlo... Desde ya, muchas gracias por leerme 

Perdón por las molestias

**Comment by mrh0wl** [comment]
Contactame a través de twitter: @SecMare
